name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install PDM
        run: |
          pip install --user pdm

      - name: Cache PDM packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pdm
          key: ${{ runner.os }}-pdm-${{ matrix.python-version }}-${{ hashFiles('pdm.lock') }}
          restore-keys: ${{ runner.os }}-pdm-${{ matrix.python-version }}-

      - name: Install dependencies
        run: pdm install

      - name: Lint code
        run: pdm run lint
      
      - name: Run tests
        run: pdm run test
