name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Install PDM
        run: |
          pip install --user pdm
          pdm self update
      
      - name: Install dependencies
        run: pdm install

      - name: Cache PDM packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pdm
          key: ${{ runner.os }}-pdm-${{ hashFiles('pdm.lock') }}
          restore-keys: ${{ runner.os }}-pdm-

      - name: Lint code
        run: pdm run lint

      - name: Run tests
        run: pdm run tox
